[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prevalidador"
version = "0.1.1"
description = "Sistema de prevalidación de cargas masivas en Excel basado en reglas JSON y catálogos externos"
authors = [{ name = "Manuel Aranzazu", email = "tu_email@dominio.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pandas>=2.0", "openpyxl>=3.1"]

[project.urls]
Homepage = "https://github.com/tu_usuario/prevalidador"
Repository = "https://github.com/tu_usuario/prevalidador"

[project.scripts]
prevalidar = "prevalidador.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
prevalidador = ["config/**/*.json", "config/**/*.xlsx", "config/**/*.csv"]

